# Generated by Django 5.1.7 on 2025-04-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="类型名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="类型描述")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="category.category",
                        verbose_name="父级类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源类型",
                "verbose_name_plural": "资源类型",
                "indexes": [models.Index(fields=["name"], name="type_name_idx")],
            },
        ),
    ]
