# Generated by Django 5.1.7 on 2025-04-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "资源类型",
                "verbose_name_plural": "资源类型",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序顺序"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["order"], name="type_order_idx"),
        ),
    ]
