# Generated by Django 5.1.7 on 2025-10-28 00:47

from django.db import migrations


def flatten_categories(apps, schema_editor):
    """
    将多层嵌套的分类结构扁平化为单层结构

    处理逻辑：
    1. 找出所有有 parent 的分类（子分类）
    2. 将这些子分类关联的文章转移到父分类
    3. 删除所有子分类
    """
    Category = apps.get_model('category', 'Category')
    Article = apps.get_model('article', 'Article')

    # 获取所有子分类（有parent的）
    child_categories = Category.objects.filter(
        parent__isnull=False).select_related('parent')

    migration_info = []

    for child_category in child_categories:
        parent_category = child_category.parent

        # 统计该子分类下的文章数量
        article_count = Article.objects.filter(category=child_category).count()

        if article_count > 0:
            # 将所有关联到子分类的文章转移到父分类
            updated_count = Article.objects.filter(category=child_category).update(
                category=parent_category
            )
            migration_info.append(
                f"将 {article_count} 篇文章从 '{child_category.name}' 转移到 '{parent_category.name}'"
            )

        # 记录删除信息
        migration_info.append(
            f"删除子分类: '{child_category.name}' (ID: {child_category.id})")

    # 删除所有子分类
    deleted_count = Category.objects.filter(parent__isnull=False).delete()[0]

    # 打印迁移信息
    if migration_info:
        print("\n=== 分类扁平化迁移信息 ===")
        for info in migration_info:
            print(f"  - {info}")
        print(f"总共删除了 {deleted_count} 个子分类\n")
    else:
        print("\n=== 分类扁平化迁移信息 ===")
        print("  - 没有需要迁移的子分类")
        print()


def reverse_flatten_categories(apps, schema_editor):
    """
    回滚操作：由于数据已经合并，无法完全还原
    这个函数只是为了满足 Django 迁移的要求
    实际回滚需要从备份恢复
    """
    print("\n警告: 此迁移不支持自动回滚！")
    print("如需回滚，请从数据库备份恢复\n")
    raise Exception("此迁移不支持自动回滚，请使用数据库备份进行恢复")


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_category_order_and_more'),
        ('article', '0004_alter_article_cover_img'),  # 确保 article 应用已迁移
    ]

    operations = [
        migrations.RunPython(flatten_categories, reverse_flatten_categories),
    ]
