# Generated by Django 5.1.7 on 2025-10-28 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_flatten_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
