# Generated by Django 5.1.7 on 2025-04-08 02:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                (
                    "photo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="封面"
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="内容"
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        default="网络", max_length=100, verbose_name="来源"
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                ("is_valid", models.BooleanField(default=True, verbose_name="有效")),
                (
                    "check_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次检查状态时间"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="category.category",
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="articles", to="tag.tag", verbose_name="资源标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "资源",
                "verbose_name_plural": "资源",
                "ordering": ["-update_time"],
                "indexes": [models.Index(fields=["name"], name="name_idx")],
            },
        ),
    ]
