# Generated by Django 5.1.7 on 2025-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="photo",
        ),
        migrations.AddField(
            model_name="article",
            name="cover_img",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="", verbose_name="封面"
            ),
        ),
    ]
