# Generated by Django 5.1.7 on 2025-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_remove_article_photo_article_cover_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.IntegerField(
                choices=[(0, "待审核"), (1, "已发布"), (3, "已下架")],
                default=0,
                verbose_name="状态",
            ),
        ),
    ]
