# Generated by Django 5.1.7 on 2025-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_article_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_img",
            field=models.ImageField(
                blank=True,
                max_length=200,
                null=True,
                upload_to="article",
                verbose_name="封面",
            ),
        ),
    ]
