# Generated by Django 5.1.7 on 2025-10-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('keyword', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='搜索关键词')),
                ('count', models.IntegerField(default=1, verbose_name='搜索次数')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='最后搜索时间')),
            ],
            options={
                'verbose_name': '搜索关键词',
                'verbose_name_plural': '搜索关键词',
                'ordering': ['-count', '-last_searched'],
                'indexes': [models.Index(fields=['-count', '-last_searched'], name='search_trending_idx')],
            },
        ),
    ]
