"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载.env文件
# dotenv.load_dotenv(os.path.join(BASE_DIR, '.env'))
dotenv.load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-default-key-for-dev-sjsgsgsg837377')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']  # 允许所有主机 - 生产环境应该限制

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third part
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'ckeditor',
    'ckeditor_uploader',
    'debug_toolbar',
    'django_extensions',
    'drf_yasg',
    'corsheaders',  # 添加CORS支持
    # apps
    'article',
    'category',
    'tag',
    'resource_website',
    'search',  # 搜索功能
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件必须放在CommonMiddleware之前
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'config.middleware.RequestLoggingMiddleware',  # 添加请求日志中间件
]

# CORS配置
CORS_ALLOW_ALL_ORIGINS = True  # 允许所有源

# 如果不允许所有源，则使用指定的源列表
if not CORS_ALLOW_ALL_ORIGINS and 'CORS_ALLOWED_ORIGINS' in os.environ:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS',
                                          '').split(',')

# 允许的请求方法
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_EXPOSE_HEADERS = [
    "content-disposition",
]

CORS_ALLOW_CREDENTIALS = True

# 允许携带认证信息（cookies、HTTP认证）跨域
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS',
                                        'True') == 'True'

INTERNAL_IPS = ['127.0.0.1']  # 本地调试IP

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'category.context_processors.all_categories',
                'tag.context_processors.all_tags',
                'article.context_processors.article_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

useSqlite = os.environ.get('USE_SQLITE',
                           'False') == 'True'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE',
                                 'django.db.backends.mysql'),
        'NAME': os.environ.get('DATABASE_NAME', ''),
        'USER': os.environ.get('DATABASE_USER', ''),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
        'HOST': os.environ.get('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DATABASE_PORT', '3306'),
    }
} if not useSqlite else {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 指定使用 sqlite3
        'NAME': BASE_DIR / 'db.sqlite3',         # 数据库文件位置
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 国际化设置（语言、时区）
LANGUAGE_CODE = 'zh-hans'  # 中文简体
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 生产环境收集目录
STATICFILES_DIRS = [BASE_DIR / 'static']  # 开发环境静态文件目录

# 媒体文件路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_UPLOAD_PATH = 'ckeditor_uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',  # 添加排序过滤器
    ],
    'DEFAULT_PAGINATION_CLASS':
    'common.pagination.CustomPageNumberPagination',
    'PAGE_SIZE':
    20,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'common.renderers.CustomJSONRenderer',
    ],
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar':
        'Custom',
        'toolbar_Custom': [['Bold', 'Italic', 'Underline'],
                           ['NumberedList', 'BulletedList', '-', 'Blockquote'],
                           ['Link', 'Unlink'], ['Image', 'Upload'],
                           ['RemoveFormat', 'Source']],
        'height':
        800,
        'width':
        1200,
        'filebrowserUploadUrl':
        '/ckeditor/upload/',  # 上传路由[1](@ref)
        'extraPlugins':
        'uploadimage'  # 启用上传插件[6](@ref)
    }
}

# 可选：设置文档权限（生产环境建议关闭）
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,  # 禁用 Django 会话认证
}

# 添加JWT设置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':
    timedelta(days=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_DAYS',
                                      30))),  # 访问令牌有效期
    'REFRESH_TOKEN_LIFETIME':
    timedelta(days=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS',
                                      365))),  # 刷新令牌有效期
    'ROTATE_REFRESH_TOKENS':
    False,
    'BLACKLIST_AFTER_ROTATION':
    False,
    'UPDATE_LAST_LOGIN':
    False,
    'ALGORITHM':
    'HS256',
    'SIGNING_KEY':
    SECRET_KEY,
    'VERIFYING_KEY':
    None,
    'AUDIENCE':
    None,
    'ISSUER':
    None,
    'JWK_URL':
    None,
    'LEEWAY':
    0,
    'AUTH_HEADER_TYPES': ('Bearer', ),
    'AUTH_HEADER_NAME':
    'HTTP_AUTHORIZATION',
    'USER_ID_FIELD':
    'id',
    'USER_ID_CLAIM':
    'user_id',
    'USER_AUTHENTICATION_RULE':
    'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken', ),
    'TOKEN_TYPE_CLAIM':
    'token_type',
    'TOKEN_USER_CLASS':
    'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM':
    'jti',
}

LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# 日志级别可通过环境变量配置
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO' if not DEBUG else 'DEBUG')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
        'request': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'request_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'request.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 5,
            'formatter': 'request',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'article': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'category': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'tag': {
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'request': {
            'handlers': ['console', 'request_file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        '': {  # 根日志器，捕获所有未指定的日志
            'handlers': ['console', 'file', 'error_file'],
            'level': LOG_LEVEL,
        },
    },
}

CSRF_TRUSTED_ORIGINS = [
    'https://www.lxziyuan.com',
    'https://lxziyuan.com'
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
