# Generated by Django 5.1.7 on 2025-10-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcewebsite',
            name='tags',
        ),
        migrations.AlterField(
            model_name='resourcewebsite',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '已发布'), (2, '已禁用')], default=1, verbose_name='状态'),
        ),
    ]
