# Generated by Django 5.1.7 on 2025-04-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "synonyms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON格式的标签同义词列表",
                        verbose_name="同义词",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源标签",
                "verbose_name_plural": "资源标签",
                "ordering": ["-created_time"],
            },
        ),
    ]
